CREATE TABLE [dbo].[Asignaturas] (
    [ID_ASIGNAURA] INT           IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       VARCHAR (100) CONSTRAINT [DF_ASIGNATURAS_NOMBRE] DEFAULT ('') NOT NULL,
    [ACTIVO]       BIT           CONSTRAINT [DF_ASIGNATURAS_ACTIVO] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_ASIGNATURAS] PRIMARY KEY CLUSTERED ([ID_ASIGNAURA] ASC)
);

