CREATE TABLE [dbo].[Calificaciones] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [IdEstudiante] INT            NOT NULL,
    [IdAsignatura] INT            CONSTRAINT [DF__CALIFICAC__MATER__5165187F] DEFAULT ('') NOT NULL,
    [Corte]        SMALLINT       CONSTRAINT [DF__CALIFICAC__PERIO__52593CB8] DEFAULT ((0)) NOT NULL,
    [Nota]         DECIMAL (2, 2) CONSTRAINT [DF__CALIFICACI__NOTA__534D60F1] DEFAULT ((0)) NOT NULL,
    [Activo]       BIT            CONSTRAINT [DF__CALIFICAC__ACTIV__5441852A] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_CALIFICACIONES] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CALIFICACIONES_ASIGNATURAS] FOREIGN KEY ([IdAsignatura]) REFERENCES [dbo].[Asignaturas] ([Id]),
    CONSTRAINT [FK_CALIFICACIONES_ESTUDIANTES] FOREIGN KEY ([IdEstudiante]) REFERENCES [dbo].[Estudiantes] ([Id])
);





