CREATE TABLE [dbo].[Calificaciones] (
    [ID_CALIFICACION] INT            IDENTITY (1, 1) NOT NULL,
    [ID_ESTUDIANTE]   INT            NOT NULL,
    [ID_ASIGNATURA]   INT            CONSTRAINT [DF__CALIFICAC__MATER__5165187F] DEFAULT ('') NOT NULL,
    [PERIODO]         INT            CONSTRAINT [DF__CALIFICAC__PERIO__52593CB8] DEFAULT ((0)) NOT NULL,
    [NOTA]            DECIMAL (1, 1) CONSTRAINT [DF__CALIFICACI__NOTA__534D60F1] DEFAULT ((0)) NOT NULL,
    [ACTIVO]          INT            CONSTRAINT [DF__CALIFICAC__ACTIV__5441852A] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_CALIFICACIONES] PRIMARY KEY CLUSTERED ([ID_CALIFICACION] ASC),
    CONSTRAINT [FK_CALIFICACIONES_ASIGNATURAS] FOREIGN KEY ([ID_ASIGNATURA]) REFERENCES [dbo].[Asignaturas] ([ID_ASIGNAURA]),
    CONSTRAINT [FK_CALIFICACIONES_ESTUDIANTES] FOREIGN KEY ([ID_CALIFICACION]) REFERENCES [dbo].[Estudiantes] ([ID_ESTUDIANTE])
);

